version: '2'
services:
    kafdrop:
        image: obsidiandynamics/kafdrop
        restart: 'no'
        ports:
            - '9000:9000'
        environment:
            KAFKA_BROKERCONNECT: 'kafka1:29092,kafka2:39092'
        depends_on:
            - 'kafka1'
            - 'kafka2'
    kafka1:
        image: obsidiandynamics/kafka
        restart: 'no'
        ports:
            - '9092:9092' # Kafka external port
            - '29092:29092' # Kafka internal port
        environment:
            KAFKA_LISTENERS: 'INTERNAL://:29092,EXTERNAL://:9092'
            KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka1:29092,EXTERNAL://localhost:9092'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
            KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_BROKER_ID: 1
        depends_on:
            - zookeeper
    kafka2:
        image: obsidiandynamics/kafka
        restart: 'no'
        ports:
            - '9093:9093' # Kafka external port
            - '39092:39092' # Kafka internal port
        environment:
            KAFKA_LISTENERS: 'INTERNAL://:39092,EXTERNAL://:9093'
            KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka2:39092,EXTERNAL://localhost:9093'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
            KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_BROKER_ID: 2
        depends_on:
            - zookeeper
    zookeeper:
        image: wurstmeister/zookeeper
        restart: 'no'
        ports:
            - '2181:2181'
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
